blank_issues_enabled: true
contact_links:
  - about: Have questions about a tutorial? Ask here! (For bugs, please use the "Bug Report" option.)
    name: Tutorial Content Help (Github Discussion)
    url: https://github.com/blockbash/blockbash/discussions/new?category=tutorial-content-help
  - about: Have questions about a tutorial? Ask here! (For bugs, please use the "Bug Report" option.)
    name: Tutorial Content Help (Chat)
    url: https://matrix.to/#/#blockbash:gitter.im
