blank_issues_enabled: true
contact_links:
  - about: You can ask for help here!
    name: Start a discussion
    url: https://github.com/orgs/blockbash/discussions/new?category=help
  - about: You can ask for help here!
    name: Ask on Gitter
    url: https://matrix.to/#/#blockbash:gitter.im
