#!/usr/bin/env bash

# ##############################################################################
: << COMMENT

PURPOSE: Invoke build process locally with blockbash-related credentials.
- credentials are supplied via 1password credential helper
AUDIENCE: For maintainer use only
MNEMONIC:
- Block
- Bash
- Act
- Credentials

COMMENT
# ##############################################################################

# shellcheck source=./../../../packages/common/scripts/source-all.sh

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./../shared.sh
. "${script_dir}/../shared.sh"

main() {
  execute_local_build_init_logic
  (cd "${blockbash_root_dir_path}" && bash "${build_scripts_act_dir_path}/execute-workflow.sh" \
    --activate_1password="${true}" \
    --cloudflare_token_base64="${null}" \
    --cosign_key_base64="${null}" \
    --cosign_password_base64="${null}" \
    --blockbash_app_private_key_base64="${null}" \
    --github_token="${null}" \
    --workflow_variant="${act_workflow_variant_null}")
}

# https://unix.stackexchange.com/a/333204
# Pipes stderr to terminal (and log file)
exec 3>&1
main 2>&1 >&3 | tee -a "${bash_log_file_path}"
