#!/usr/bin/env bash

# ##############################################################################
: << COMMENT

PURPOSE: Initialize Blockbash project.
- Create configuration files for local development
- Install dependencies
- This should be called before any build operation.

COMMENT
# ##############################################################################

# shellcheck source=./../../../packages/common/scripts/source-all.sh

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./../shared.sh
. "${script_dir}/../shared.sh"

main() {
  cd "${blockbash_root_dir_path}" || die "Couldn't cd into ${blockbash_root_dir_path}"

  log_debug "Installing dependencies"
  pnpm install

  log_debug "Compiling Solidity contracts and generating contract types"
  pnpm run --filter @blockbash/lab-core contract:compile

  # create_challenge_metadata_file: Use branch-related value (within override.env) by default
  create_configurations "${BLOCKBASH_GLOBAL_BRANCH_NAME:-$(get_current_git_branch)}"
}

# https://unix.stackexchange.com/a/333204
# Pipes stderr to terminal (and log file)
exec 3>&1
main 2>&1 >&3 | tee -a "${bash_log_file_path}"
