#!/usr/bin/env bash

# ##############################################################################
: << COMMENT

PURPOSE: Generate FE embeddable hardhat-tracer traces for bb_current_lab_guid_bash
- Outputs go to lab-core/outputs/hardhat-tracer/*
- View create-website-build.sh comments for more context.
PREREQUISITES:
- Executing bb-act-no-cred/bb-act-cred
- Setting bb_current_lab_guid_bash

COMMENT
# ##############################################################################

# shellcheck source=./../../../packages/common/scripts/source-all.sh

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./../shared.sh
. "${script_dir}/../shared.sh"

main() {
  cd "${blockbash_root_dir_path}" || die "Couldn't cd into ${blockbash_root_dir_path}"

  init_outputs
  bb-lab --script-file-path="${container_build_scripts_dir_path}/create-contract-traces.sh"
}

# https://unix.stackexchange.com/a/333204
# Pipes stderr to terminal (and log file)
exec 3>&1
main 2>&1 >&3 | tee -a "${bash_log_file_path}"
