#!/usr/bin/env bash

# ##############################################################################
: << COMMENT

PURPOSE: Initialize website for local development.
- View create-website-build.sh comments for more context.

COMMENT
# ##############################################################################

# shellcheck source=./../../../packages/common/scripts/source-all.sh

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
# shellcheck source=./../shared.sh
. "${script_dir}/../shared.sh"

main() {
  cd "${blockbash_root_dir_path}" || die "Couldn't cd into ${blockbash_root_dir_path}"

  # Use nodemon as certain files aren't monitored by docusaurus' automatic reload capability.
  # nodemon leverages nodemon.json for configuration.
  pnpm --filter @blockbash/website exec nodemon --exec "cd ${blockbash_root_dir_path} && bash ${build_scripts_workflow_steps_dir_path}/create-website-build.sh --is_interactive_shell=true"
}

# https://unix.stackexchange.com/a/333204
# Pipes stderr to terminal (and log file)
exec 3>&1
main 2>&1 >&3 | tee -a "${bash_log_file_path}"
