# ##############################################################################
# PURPOSE: Create lab repos in "labs" Github Org
# - Each lab needs a separate repo so we can create URIs like `https://vscode.dev/redirect?url=vscode://ms-vscode-remote.remote-containers/cloneInVolume?url=https://github.com/blockbash-labs-dev/reentrancy-fundamentals-attack`
# ##############################################################################

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      is_enabled:
        required: true
        type: string
      lab_dir_path:
        required: true
        type: string
      primary_json_string:
        required: true
        type: string
    secrets:
      BLOCKBASH_APP_PRIVATE_KEY_BASE64:
        required: true

jobs:
  create_lab_repos:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-22.04
    steps:
      - id: "null"
        if: ${{ false }}
        # language=sh
        run: |
          # Hacky way for GITHUB WORKFLOW plugin to recognize GITHUB_ENV
          # echo "build_scripts_workflow_steps_dir_path=null" >> $GITHUB_ENV
          # echo "should_publish=null" >> $GITHUB_ENV
          # echo "github_labs_org_app_id=null" >> $GITHUB_ENV
          # echo "github_labs_org_name=null" >> $GITHUB_ENV
          # echo "BLOCKBASH_APP_PRIVATE_KEY_BASE64=null" >> $GITHUB_ENV
        shell: bash
      # See commentary in create-deployment.yaml as to why we are doing this if
      # statement on all job steps
      - if: inputs.is_enabled == 'true'
        name: Checkout (GitHub)
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - if: inputs.is_enabled == 'true'
        name: Job Init
        uses: ./.github/workflows/composite-actions/job-init
        with:
          blockbash_app_private_key_base64: ${{ secrets.BLOCKBASH_APP_PRIVATE_KEY_BASE64 }}
          primary_json_string: ${{ inputs.primary_json_string }}
      - if: inputs.is_enabled == 'true' && env.should_publish == 'true'
        name: create-github-app-env-vars
        # language=sh
        run: |
          bash "${build_scripts_workflow_steps_dir_path}/create-github-app-env-vars.sh"
      - id: generate_token
        if: inputs.is_enabled == 'true' && env.should_publish == 'true'
        name: create-github-app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ env.github_labs_org_app_id }}
          owner: ${{ env.github_labs_org_name }}
          private-key: ${{ env.BLOCKBASH_APP_PRIVATE_KEY_BASE64 }}
      - if: inputs.is_enabled == 'true' && env.should_publish == 'true'
        # Need to run "Job Init" again as we need to register the token created
        # within generate_token
        name: Job Init
        uses: ./.github/workflows/composite-actions/job-init
        with:
          _github_token: ${{ steps.generate_token.outputs.token }}
          primary_json_string: ${{ inputs.primary_json_string }}
      - id: create_repo_sync_file
        if: inputs.is_enabled == 'true'
        name: Create Repo Sync File
        # language=sh
        run: |
          bash "${build_scripts_workflow_steps_dir_path}/create-repo-sync-file.sh" \
              --branch_name=${branch_name} \
              --lab_environment_dir_path='${{ inputs.lab_dir_path }}'
      - id: create_repo
        if: inputs.is_enabled == 'true' && env.should_publish == 'true'
        name: Create Repo
        # language=sh
        run: |
          bash "${build_scripts_workflow_steps_dir_path}/create-lab-repo.sh" \
            --lab_environment_dir_path='${{ inputs.lab_dir_path }}' \
            --branch_name=${branch_name}
      - if: inputs.is_enabled == 'true' && env.should_publish == 'true'
        name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          COMMIT_BODY: syncing lab files
          GH_INSTALLATION_TOKEN: ${{ steps.generate_token.outputs.token }}
          ORIGINAL_MESSAGE: false
          SKIP_PR: true
      - id: cleanup_actions
        if: inputs.is_enabled == 'true' && always()
        name: Execute Cleanup Actions
        # language=sh
        run: |
          bash '${{ env.build_scripts_workflow_steps_dir_path }}/cleanup-job.sh' \
            --is_docker_build="false"
